# Well you wanna make sure that your package.json has a homepage pointer to the entry point in the application.
on:
  push:
    branches:
      - "site" # change to the branch you wish to deploy from

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - id: build-publish
      uses: bitovi/github-actions-react-to-github-pages@v1.2.0
      with:
        path: build # change to your build folder
